# Gin-Vue-Admin Global Configuration

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'


wxapp:
    secret: ''
    appid: ''

# mysql connect configurationm
gin:
  mode: "debug"

dataBase:
  type: ''
  username: ''
  password: ''
  path: ''
  dbname: ''
  config: ''
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true

#sqlite 配置
sqlite:
  path: db.db
  log-mode: true
  config: 'loc=Asia/Shanghai'


redis:
  addr: '127.0.0.1:6379'
  db: 0

# system configuration
system:
  use-multipoint: false
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: ""  # support mysql/sqlite

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

# logger configuration
log:
  prefix: '[pcr-web]'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'



